### ISSUE TITLE
Tool failing at Step 2, post slugs load but not post images.

### ISSUE THREAD

**Issue by katelynae** [Jazilch/hubspot-web-scraper#8]
I've been trying to run the tool with this blog - https://www.hycu.com/blog/ (HubSpot blog - http://685119.hs-sites.com/blog)

I get to step 2 and it finds the page slugs for the posts but only the first post image appears, the rest are blank. When I click 'Next' at this step the tool fails. See video below:

https://www.loom.com/share/92c826d3a58f415c9d347d4e75ac29da

**Comment by Jazilch** [comment]
I took a look at this and it looks like the images are being lazy loaded in. For some reason the first image is not lazy loaded and that is why we are able to get the first image but not the rest of the images. It looks like the image source is on `data-original` attribute on the selector of the image. This might be an edge case we might not be able to solve for as I haven't seen this attribute used before. 

We should probably think about handling this but most of the time when I see images lazy loaded into the page the attribute is `data-src` and not `data-original`. If we can find more examples of other blogs using `data-original` we should add this to the app but I don't we should solve for such an edge case of this attribute.

**Comment by katelynae** [comment]
Thanks, James for taking a look, and thank you for the extra info on how to spot lazy loaded images, I'll know to keep an eye out for this for future blogs!
